### Add new user
PUT http://localhost:3000/api/user/user
Content-Type: application/json

{
  "email": "example@email.org",
  "password": "12345678"
}

### Delete user
DELETE http://localhost:3000/api/user/user/example@email.org

